#!/bin/env sh

## Get Brightness
get_blight() {
    while true; do
    echo "$(xbacklight -get)"
        sleep 1
    done
}

## Set Brightness
set_blight() {
  xbacklight -set $1
}



if [[ "$1" == "--get" ]]; then
    get_blight
elif [[ "$1" == "--set" ]]; then
    set_blight "$2"
fi
