#!/bin/env sh

get_blight() {
    while true; do
        MAX=$(brightnessctl m)
        CURR=$(brightnessctl g)
        echo $((CURR * 100 / MAX))
        sleep 1
    done
}

set_blight() {
    brightnessctl set "$1%"
    # Fire swayosd so the overlay shows when eww slider is used too
    swayosd-client --brightness set "$1"
}

if [[ "$1" == "--get" ]]; then
    get_blight
elif [[ "$1" == "--set" ]]; then
    set_blight "$2"
fi
