#!/bin/env sh

FILE="$HOME/.cache/eww_launch.xyz"
CFG="$HOME/.config/eww/bar"
EWW="/usr/bin/eww --config "$CFG""

## Open widgets
run_eww() {
    ${EWW} open-many \
         bar
}

## Launch or close widgets accordingly
if [ ! -f "$FILE" ]; then
    touch "$FILE"
    run_eww --screen 0
else
    ${EWW} close-all && killall eww
    rm "$FILE"
fi
