#!/bin/env sh

## Toggle state
toggle() {
  if [ "$(nmcli g | grep -oE "disconnected")" ];then
#  if [ -z "$(connmanctl state | grep -e 'ready|online')" ];then
    nmcli radio wifi off
#    connmanctl enable wifi
  else
    nmcli radio wifi off
#    connmanctl disable wifi
  fi
}

## Get Icon
get_icon() {
  while true; do
    if [ "$(nmcli g | grep -oE "disconnected")" ];then
#    if [ "$(connmanctl state | grep -E 'ready|online')" ];then
      echo "󰖪"
    else
      echo "󰖩"
    fi
    sleep 5
  done
}

## Get Status
get_status() {
  while true; do
    if [ "$(nmcli g | grep -oE "disconnected")" ];then
 #   if [ -z "$(connmanctl state | grep -E 'ready|online')" ];then
      echo "󰖪  Offline"
    else
      echo "󰖩  $(nmcli c | grep wlan0 | awk '{print ($1)}')"
    fi
    sleep 5
  done
}



if [ "$1" = "--toggle" ]; then
  toggle
elif [ "$1" = "--icon" ]; then
  get_icon
else #default
  get_status
fi

