#!/usr/bin/zsh

DOTS="$HOME/documents/.bc/batcave/dotfiles"

[ ! -f "$HOME/.config" ] && mkdir "$HOME/.config"
[ ! -f "$HOME/.local/share" ] && mkdir -p "$HOME/.local/share"

rm -rf $HOME/{.zshrc,.bashrc,.profile,.login}

ln -sv "$DOTS/.local/myBin" "$HOME/.local/bin/"

"$HOME/.local/bin/myBin/set-w"

for i in $(ls "$DOTS/.config"); do
    rm -rf "$HOME/.config/$i" &&
        ln -sv "$DOTS/.config/$i" "$HOME/.config/"
done

sudo-askpass cat zshenv >>'/etc/zsh/zshenv'
