#!/bin/sh

# Base PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/ccache/bin:$PATH"
export PATH="$HOME/.local/bin:$HOME/.local/bin/myBin:$HOME/.local/share/npm/bin:$HOME/.config/composer/vendor/bin:$HOME/.nix-profile/bin:$PATH"

# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(fd --type d . $HOME/.local/bin/myBin/ | paste -sd ':' -)"
export PATH="$PATH:$(go env GOBIN):$(go env GOPATH)/bin"

# --- 1. XDG BASE DIRECTORY SPECIFICATION ---
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.local/cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="/run/user/$UID"

# --- 2. XDG COMPLIANT TOOLCHAIN & APP PATHS ---
# Security
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"

# Toolchains (Go, Rust, Node, Python, Perl, Java)
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export NVM_DIR="$XDG_DATA_HOME/nvm"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export PYTHONHISTFILE="$XDG_STATE_HOME/python/history"
export PERL_LOCAL_LIB_ROOT="$XDG_DATA_HOME/perl5"
export PERL_MB_OPT="--install_base \"$XDG_DATA_HOME/perl5\""
export PERL_MM_OPT="INSTALL_BASE=$XDG_DATA_HOME/perl5"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"

# System Utilities & Logging
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripgreprc"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export GDBHISTFILE="$XDG_DATA_HOME/gdb/history"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_STATE_HOME/zsh/history"
export LESSHISTFILE="-"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"

# Media & Specific Apps
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export NOTES_DIR="$HOME/documents/batcave/notes"

# GUI / X11 Fallbacks
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XSERVERRC="$XDG_CONFIG_HOME/x11/xserverrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export XCURSOR_PATH="$XDG_DATA_HOME/icons"
export XDG_DATA_DIRS="$HOME/.nix-profile/share:$XDG_DATA_DIRS"

# --- 3. DEFAULT PROGRAMS ---
if [ -n "$SSH_CONNECTION" ]; then
    export EDITOR='vim'
else
    export EDITOR='nvim'
fi

export SHELL='/usr/bin/zsh'
export PAGER='nvim +Man!'
export MANPAGER='nvim +Man!'
export TERMINAL='ghostty'
export BROWSER='floorp'
export BROWSERCLI='w3m'
export READER='zathura'
export IMAGEVIEWER='nsxiv'
export VIDEOPLAYER='mpv'
export FILE='lf'
export COLORTERM='truecolor'
export OPENER='xdg-open'

# --- 4. BEHAVIOR & THEME ---
export GPG_TTY=$(tty)
export QT_QPA_PLATFORMTHEME='qt5ct'
export GTK_THEME='Numix:dark'
export XCURSOR_THEME='Numix-Cursor-Light'
export XCURSOR_SIZE='28px'
export WINEFSYNC=1
export MAILSYNC_MUTE=1
export MOZ_USE_XINPUT2=1
export AWT_TOOLKIT="MToolkit wmname LG3D"
export _JAVA_AWT_WM_NONREPARENTING=1
export CHROME_PATH='/usr/bin/brave'
export NIXPKGS_ALLOW_UNFREE=1
export LIBSEAT_BACKEND='logind'
export VALET_CONFIG_PATH="$XDG_CONFIG_HOME/valet"
export DICS='/usr/share/stardict/dic/'
export LESS="-R"

# FZF Interface
export FZF_DEFAULT_COMMAND='fd --type file --hidden --no-ignore'
export FZF_DEFAULT_OPTS="--layout=reverse --height 40% --preview 'bat --color=always {}'"
export FZF_CTRL_T_OPTS="--select-1 --exit-0 --preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '?:toggle-preview'"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

# Less Colors
export LESS_TERMCAP_mb="$(printf '%b' '\e[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '\e[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '\e[0m')"
export LESS_TERMCAP_so="$(printf '%b' '\e[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '\e[0m')"
export LESS_TERMCAP_us="$(printf '%b' '\e[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '\e[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"

# Miscellaneous Paths
export MANPATH="$MANPATH:/usr/local/man:"
export CDPATH="$CDPATH:.:$HOME/documents/.bc"

# Security Execution
export SUDO_ASKPASS="$XDG_DATA_HOME/bin/myBin/menu/dmenupass"
export DOAS_ASKPASS='bemenu --password hide --ignorecase --bottom --line-height 30 --fn "JetBrainsMonoNerdFontMono 14" --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa" --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c"'

# Shortcuts mapping
[ ! -f "$XDG_CONFIG_HOME/shell/shortcutrc" ] && setsid -f shortcuts >/dev/null 2>&1
