#!/bin/env sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

[ -f $HOME/documents/batcave/dotfiles/zshenv ] && . $HOME/documents/batcave/dotfiles/zshenv
[ -f $XDG_CONFIG_HOME/x11/xprofile ] && . $XDG_CONFIG_HOME/x11/xprofile

#dont seem to work
USERXSESSION="$XDG_CACHE_HOME/x11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/x11/xsessionrc"
ALTUSERXSESSION="$XDG_CACHE_HOME/x11/Xsession"
ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"

userresources="$XDG_CONFIG_HOME/x11/xresources"
usermodmap="$XDG_CONFIG_HOME/x11/xmodmap"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

eval $(/usr/bin/gpg-agent --daemon)
#eval $(ssh-agent)

get_session(){
	local dbus_args=(--sh-syntax --exit-with-session)
	case "dwm" in
		bspwm) dbus_args+=(ssh-agent bspwm-session) ;;
		dwm) dbus_args+=(ssh-agent dwm) ;;
		xfce) dbus_args+=(ssh-agent xfce4-session) ;;
		*) dbus_args+=("ssh-agent $WM") ;;
	esac

	echo "dbus-launch ${dbus_args[*]}"
}

exec $(get_session)
