#!/bin/env sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

[[ -f ~/.config/shell/profile ]] && source ~/.config/shell/profile

picom &		#run the compton copmpositing manager
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
redshift &
/usr/lib/geoclue-2.0/demos/agent &
$HOME/.local/bin/setbg &			# set the background with the `setbg` script
dwmblocks &
#remaps &		# run the remaps script, switching caps/esc and more; check it for more info
# mpd-module-update &	# Check for when to update the mpd module
#sh ~/.config/autostart-scripts/tty-color.sh &
