#!/bin/env sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

[ ! -f $XDG_CONFIG_HOME/shell/profile ] && . $XDG_CONFIG_HOME/shell/profile

picom --experimental-backends &		#run the compton copmpositing manager
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
xss-lock -- slock &
unclutter &		# Remove mouse when idle
redshift &
/usr/lib/geoclue-2.0/demos/agent &
polkit-dumb-agent &
#$HOME/.local/bin/setbg &	# set the background with the `setbg` script
#dwmblocks &
/usr/bin/pipewire &
#sh ~/.config/autostart-scripts/tty-color.sh &
