#!/bin/sh

kill_wp() {
    cd /opt/devilbox || exit &&
        (
            docker-compose stop
            docker-compose rm -f
        )
    rm -rf /tmp/dvlbx.pid
}

start_max() {
    echo "dvl_up" >/tmp/dvlbx.pid &&
        cd /opt/devilbox/ || exit && docker-compose up -d
}

start_min() {
    echo "dvl_up" >/tmp/dvlbx.pid &&
        cd /opt/devilbox/ || exit && docker-compose up -d bind httpd php mysql
}

ask_start() {
    CHOICE="$(printf "Max\\nMin\\nKill" | bemenu --prompt "> " --line-height 55 --fn "JetBrainsMonoNerdFontMono 20" --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa" --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c")"
    case "$CHOICE" in
    Max) start_max ;;
    Min) start_min ;;
    Kill) kill_wp ;;
    esac
}

ask_end() {
    CHOICE=$(printf "No\\nYes" | bemenu --prompt "Kill dvlbx? " --line-height 55 --fn "JetBrainsMonoNerdFontMono 20" --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa" --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c") &&
        [ "$CHOICE" = "Yes" ] && kill_wp
}

case "$1" in
Max) start_max ;;
Min) start_min ;;
Kill) kill_wp ;;
*) ([ -f '/tmp/dvlbx.pid' ] && ask_end && exit) || ask_start ;;
esac
