#!/bin/sh

kill_wp() {
    cd /opt/devilbox && /docker-compose stop
}

start_max() {
    cd /opt/devilbox/ && docker-compose up -d
}

start_min() {
    cd /opt/devilbox/ && docker-compose up -d bind httpd php mysql
}

ask_start() {
    CHOICE="$(printf "Max\\nMin\\nKill" | bemenu --prompt "$1" --line-height 55 --fn "JetBrainsMonoNerdFontMono 20" --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa" --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c")"
    case "$CHOICE" in
    Max) start_max ;;
    Min) start_min ;;
    Kill) kill_wp ;;
    esac
}

ask_end() {
    CHOICE=$(printf "No\\nYes" | bemenu --prompt "$1" --line-height 55 --fn "JetBrainsMonoNerdFontMono 20" --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa" --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c") &&
        [ "$CHOICE" = "Yes" ] && kill_wp
}

case "$1" in
Max) start_max ;;
Min) start_min ;;
Kill) kill_wp ;;
*) ask_start ;;
esac
