#!/usr/bin/bash

# Ask user for theme name with bemenu as interface
THEME_NAME=$(echo "" | bemenu --prompt "Enter theme name: " --no-exec --line-height 55 --fn "JetBrainsMonoNerdFontMono 20" --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa" --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c") &&
    [[ -n $THEME_NAME ]] || exit

ADMIN_PASS=$(echo "" | bemenu --prompt "Enter admin password: " --password --line-height 55 --fn "JetBrainsMonoNerdFontMono 20" --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa" --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c") &&
    [[ -n $ADMIN_PASS ]] || exit

# Get underscores and change names in files as per instructions in repo README w/fd & sed
git clone https://github.com/Rmmichael95/Starter_Theme_WP.git /tmp/"${THEME_NAME}" 2>/tmp/us_err && {
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/'_s'/'${THEME_NAME}'/" {}
    fd . --type f --extension css /tmp/"${THEME_NAME}"/ --exec sed -i "s/Text Domain: _s/Text Domain: ${THEME_NAME}/" {}
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/ _s/ ${THEME_NAME}/" {}
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/_s-/${THEME_NAME}-/" {}
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/_S_/${THEME_NAME^^}/" {}
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/_s_/${THEME_NAME}_/" {}
}

# Zip file to import to WP
cd /tmp || exit && zip -r "${THEME_NAME}.zip" "${THEME_NAME}" || exit

notify-send 'Got Theme'

WP_PATH="${XDG_DATA_HOME}/dvlbx/data/www/${THEME_NAME}"

mkdir -p "${WP_PATH}"
mv /tmp/"${THEME_NAME}.zip" "${XDG_DATA_HOME}"/dvlbx/data/www/ || exit

rm -rf /tmp/"${THEME_NAME}"
rm -rf /tmp/us_err

cd "$XDG_DATA_HOME"/dvlbx/data/www/.wordpress &&
    git pull &&
    notify-send 'Got WordPress'

echo "${THEME_NAME}" >"${XDG_DATA_HOME}"/dvlbx/data/www/theme &&
    echo "${ADMIN_PASS}" >"${XDG_DATA_HOME}"/dvlbx/data/www/pass

doas-askpass bash -c "echo '127.0.0.1 ${THEME_NAME}.dvl.to #${THEME_NAME}' >>/etc/hosts" || exit &&
    cd /opt/devilbox || exit &&
    docker-compose exec --user devilbox php bash -l -c "(THEME_NAME=$(cat /shared/httpd/theme) \
&& ADMIN_PASS=$(cat /shared/httpd/pass) \
&& cp -r /shared/httpd/.wordpress /shared/httpd/${THEME_NAME}/wordpress \
&& ln -sv /shared/httpd/${THEME_NAME}/wordpress /shared/httpd/${THEME_NAME}/htdocs \
&& wp config create --dbname=${THEME_NAME} --dbuser=root --dbhost=mysql --path=/shared/httpd/${THEME_NAME}/htdocs \
&& wp db create --path=/shared/httpd/${THEME_NAME}/htdocs \
&& wp core install --url=https://${THEME_NAME}.dvl.to --title=${THEME_NAME} --admin_user=rmmichael95 --admin_password=${ADMIN_PASS} --admin_email=ryanmsul@protonmail.com --path=/shared/httpd/${THEME_NAME}/htdocs \
&& wp theme install /shared/httpd/${THEME_NAME}.zip --activate --path=/shared/httpd/${THEME_NAME}/htdocs \
&& cd /shared/httpd/${THEME_NAME}/htdocs/wp-content/themes/${THEME_NAME} || exit \
&& composer global require php-stubs/wordpress-globals php-stubs/wordpress-stubs php-stubs/woocommerce-stubs php-stubs/acf-pro-stubs wpsyntex/polylang-stubs php-stubs/genesis-stubs php-stubs/wp-cli-stubs)"

rm -rf "${XDG_DATA_HOME}/dvlbx/data/www/theme" "${XDG_DATA_HOME}/dvlbx/data/www/pass" "${XDG_DATA_HOME}/dvlbx/data/www/${THEME_NAME}.zip"

notify-send 'New Theme installed'
