#!/bin/sh

THEME_NAME=$(/usr/bin/ls "$XDG_DATA_HOME/dvlbx/data/www/" | bemenu --prompt "Choose theme to delete" --line-height 55 --fn "JetBrainsMonoNerdFontMono 20" --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa" --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c") &&
    [ -n "${THEME_NAME}" ] || exit

echo "${THEME_NAME}" >"${XDG_DATA_HOME}"/dvlbx/data/www/theme

doas-askpass sed -i "/#${THEME_NAME}/d" /etc/hosts &&
    cd /opt/devilbox/ &&
    docker-compose exec --user devilbox php bash -l -c "(THEME_NAME=$(cat /shared/httpd/theme) && rm -rf /shared/httpd/theme && wp db drop --path=/shared/httpd/${THEME_NAME}/htdocs)" || exit

rm -rf "${XDG_DATA_HOME}/dvlbx/data/www/${THEME_NAME}" && notify-send "Removed ${THEME_NAME} from dvlbx"
