#!/bin/bash

THEME_NAME=$(echo "Enter theme name: " | bemenu --prompt "$1" --line-height 55 --fn "JetBrainsMonoNerdFontMono 20" --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa" --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c")

THEME_NAME_U="${THEME_NAME}"
THEME_NAME_U+='_'

THEME_NAME_C="${THEME_NAME_U^^}"

THEME_NAME_D="${THEME_NAME}"
THEME_NAME_D+='-'

git clone https://github.com/Automattic/_s.git /tmp/"${THEME_NAME}" >/tmp/err && {
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/'_s'/'$THEME_NAME'/g" {}
    fd . --type f --extension css /tmp/"${THEME_NAME}"/ --exec sed -i "s/Text Domain: _s/Text Domain: $THEME_NAME/g" {}
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/ _s/ $THEME_NAME/" {}
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/_s-/$THEME_NAME_D/" {}
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/_S_/$THEME_NAME_C/" {}
    fd . --type f /tmp/"${THEME_NAME}"/ --exec sed -i "s/_s_/$THEME_NAME_U/" {}
}

THEME_NAME_Z="${THEME_NAME}"
THEME_NAME_Z+=".zip"

cd /tmp || exit && zip -r "${THEME_NAME_Z}" "${THEME_NAME}" || exit

notify-send 'Got Theme'

WP_PATH="${XDG_DATA_HOME}"/dvlbx/data/www/"${THEME_NAME}"
mkdir -p "${WP_PATH}"
mv /tmp/"${THEME_NAME_Z}" "${XDG_DATA_HOME}"/dvlbx/data/www/ || exit

rm -rf /tmp/"${THEME_NAME}"
rm -rf /tmp/err

git clone https://github.com/WordPress/WordPress.git "${WP_PATH}"/wordpress

notify-send 'Got WordPress'

THEME_NAME_P="${THEME_NAME}"
THEME_NAME_P+='.dvl.to'

echo "${THEME_NAME}" >"${XDG_DATA_HOME}"/dvlbx/data/www/theme

# && wp config create --dbname=wordpress --dbuser=root --path=/shared/httpd/"${THEME_NAME}"/htdocs \
doas-askpass bash -c "echo '127.0.0.1 $THEME_NAME_P' >>/etc/hosts" || exit &&
    cd /opt/devilbox || exit &&
    doas /usr/bin/docker-compose exec --user devilbox php bash -l -c '(THEME_NAME=`cat /shared/httpd/theme` && THEME_NAME_Z="${THEME_NAME}" && THEME_NAME_Z+='.zip' && ln -sv /shared/httpd/"${THEME_NAME}"/wordpress /shared/httpd/"${THEME_NAME}"/htdocs && cp /shared/httpd/wp-config.php /shared/httpd/"${THEME_NAME}"/htdocs && wp db create --path=/shared/httpd/"${THEME_NAME}"/htdocs && wp core install --url=https://"${THEME_NAME}".dvl.to --title="${THEME_NAME}" --admin_user=rmmichael95 --admin_email=ryanmsul@protonmail.com --path=/shared/httpd/"${THEME_NAME}"/htdocs && wp theme install /shared/httpd/"${THEME_NAME_Z}" --activate --path=/shared/httpd/"${THEME_NAME}"/htdocs && cd /shared/httpd/"${THEME_NAME}"/htdocs/wp-content/themes/"${THEME_NAME}" || exit && composer global require php-stubs/wordpress-globals php-stubs/wordpress-stubs php-stubs/woocommerce-stubs php-stubs/acf-pro-stubs wpsyntex/polylang-stubs php-stubs/genesis-stubs php-stubs/wp-cli-stubs)'

rm -rf "${XDG_DATA_HOME}"/dvlbx/data/www/theme "${XDG_DATA_HOME}"/dvlbx/data/www/"${THEME_NAME_Z}"

notify-send 'New Theme installed'
