general {
    lock_cmd = hyprlock
    #lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = ~/.local/bin/myBin/lock-pic && loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 2.5min — keyboard backlight off
listener {
    timeout = 150
    on-timeout = brightnessctl -sd white:kbd_backlight set 0
    on-resume = brightnessctl -rd white:kbd_backlight
}

# 5min — lock screen
listener {
    timeout = 300
    on-timeout = ~/.local/bin/myBin/lock-pic && loginctl lock-session
    on-resume = notify-send "Welcome back!"
}

# 5.5min — screen off + drop to power-saver
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off && powerprofilesctl set power-saver
    on-resume = hyprctl dispatch dpms on && powerprofilesctl set balanced
}

# 8min — suspend, with automatic hibernate fallback
listener {
    timeout = 480
    on-timeout = systemctl suspend-then-hibernate
}
