# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/wallpapers/garuda-wallpapers/garuda-wp-dessert-01.png'

# Special
background='#0C0201'
foreground='#ebb2b7'
cursor='#ebb2b7'

# Colors
color0='#0C0201'
color1='#0E0A4B'
color2='#BD5758'
color3='#B48D62'
color4='#C39D60'
color5='#F7877E'
color6='#DE6C82'
color7='#ebb2b7'
color8='#a47c80'
color9='#0E0A4B'
color10='#BD5758'
color11='#B48D62'
color12='#C39D60'
color13='#F7877E'
color14='#DE6C82'
color15='#ebb2b7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
