#!/usr/bin/env sh


CHOICE="$(printf "Yes\\nReboot" | bemenu --prompt "$1" --line-height 30 --tb "#15191c" --tf "#eb4d4b" --fb "#15191c" --ff "#d3c6aa" --nb "#15191c" --nf "#4b565c" --hb "#15191c" --hf "#d3c6aa" --fbb "#15191c" --fbf "#d3c6aa"  --sb "#15191c" --sf "#d3c6aa" --ab "#15191c" --af "#4b565c" --bdr "#4b565c")"

if test "$CHOICE" = "Yes"; then
    dinitctl shutdown && doas-askpass poweroff
elif test "$CHOICE" = "Reboot"; then
    dinitctl shutdown && doas-askpass reboot
fi
