#!/usr/bin/env sh

#CHOICE="$(printf "Yes\\nReboot" | dmenu -i -p "$1")"
CHOICE="$(printf "Yes\\nReboot" | dmenu -p "$1")"

if test "$CHOICE" = "Yes"; then
    dinitctl shutdown && doas-askpass poweroff
elif test "$CHOICE" = "Reboot"; then
    dinitctl shutdown && doas-askpass reboot
fi
